name: CI pipeline
on: [ push, workflow_dispatch ]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build with maven
        run: mvn clean install -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.native.container-build=true -Pnative -Dmaven.test.failure.ignore=true
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
